from snakemake.utils import min_version

#------------- min snakemake version ------------
min_version('6.7.0')

#------------- setup ------------
configfile: 'config/config.yaml'

report: 'report/workflow.rst'

#------------- load rules ------------

include: 'rules/common.smk'
include: 'rules/qc.smk'

#------------- workflow ------------

rule all:
    input:
        get_fastqc_output(),
        get_fastqscreen_output(),
        'results/qc_metrics/multiqc_report.html',
