from snakemake.utils import min_version

# ------------- min snakemake version ------------
min_version("6.7.0")


# ------------- setup ------------
configfile: "config/config.yaml"


report: "report/workflow.rst"


# ------------- load rules ------------


include: "rules/common.smk"
include: "rules/qc.smk"


if config["aligner"].lower() == "bwa":

    include: "rules/align_bwa.smk"


elif config["aligner"].lower() == "star":

    include: "rules/align_star.smk"


else:

    sys.exit("Invalid aligner selecter")


if process_from_bcl:

    include: "rules/demultiplex.smk"


# ------------- workflow ------------


if process_from_bcl:

    rule all:
        input:
            get_bcl2fastq_output(),
            get_mergelanes_output(),
            get_fastqc_output(),
            get_fastqscreen_output(),
            "results/qc_metrics/multiqc_report.html",


else:

    rule all:
        input:
            get_fastqc_output(),
            get_fastqscreen_output(),
            "results/multiqc/multiqc_report.html",
            get_align_output(),
