from snakemake.utils import min_version

# ------------- min snakemake version ------------
min_version("6.7.0")


# ------------- setup ------------
configfile: "config/config.yaml"


report: "report/workflow.rst"


# ------------- load rules ------------


include: "rules/common.smk"
include: "rules/qc.smk"


if aligner == "bwa":

    include: "rules/align_bwa.smk"


elif aligner == "star":

    include: "rules/align_star.smk"


if demultiplex or merge_without_demux:

    include: "rules/demultiplex.smk"


# ------------- workflow ------------


if demultiplex or merge_without_demux:

    if demux_tool == "mgi_splitbarcode":

        rule all:
            input:
                get_splitbarcodes_output(),
                get_mergelanes_output(),
                get_fastqc_output(),
                get_fastqscreen_output(),
                "results/multiqc/multiqc_report.html",


    else:

        rule all:
            input:
                get_mergelanes_output(),
                get_fastqc_output(),
                get_fastqscreen_output(),
                "results/multiqc/multiqc_report.html",


else:

    rule all:
        input:
            get_fastqc_output(),
            get_fastqscreen_output(),
            "results/multiqc/multiqc_report.html",
