# if set to false, will process from fastq files
demultiplex: False

# demultiplexing software (only relevant if above is true)
# valid choices are: bcl2fastq and mgi_splitbarcode
demux_tool: bcl2fastq

# sample sheet for bcl2fastq conversion
sample_sheet: raw_input/SampleSheet.csv

# directory with raw non-demultiplexed data
raw_input: raw_input

# number of sequencing lanes (only for bcl input)
lanes: 4

# Directory to start merge step from.
# Only set this if demultplexing has been done
# externally to the pipeline (leave blank otherwise)
# (a valid sheet is required to use this option)
merge_from_dir:

# directory containing fastq files
fastq_dir: fastq

# config file for Fastq Screen
FastqScreen_config: config/fastq_screen.conf

params:
    # extra commandline parameters for bcl2fastq (optional)
    bcl2fastq: >
        --mask-short-adapter-reads 22
         --minimum-trimmed-read-length 35
         --loading-theads 4
         --writing-threads 4
         --processing-theads 14
    
    # extra commandline parameters for STAR (optional)
    star:

    # parameters for MGI demultiplexing
    mgi:
        # MGI splitBarcode binary
        binary:
        # barcode file path
        bc_file:
        # split params for barcode 1: read len, barcode len, number of mismatches
        bs1: "300 10 1"
        # split params for barcode 2: read len, barcode len, number of mismatches
        bs2: "310 10 1"
        # extra parameters (-r = reverse complement barcode)
        extra: -r -m 64

# bwa or star (leave blank to skip alignment-based QC)
aligner: bwa

# fasta reference if running BWA (must also include BWA index)
ref: data/GCF_013166975.1_ASM1316697v1_genomic.fna

# only required if running STAR aligner
star_index: data/star_index

# only required if running STAR aligner
gtf: data/GCF_013166975.1_ASM1316697v1_genomic.gff
