bcl2fastq:
    threads: 16
    mem_mb: 98304
    runtime: '12h'

mergelanes:
    threads: 1
    mem_mb: 12288
    runtime: '2h'

fastqc:
    threads: 2
    mem_mb: 8192
    runtime: '12h'

fastqscreen:
    threads: 8
    mem_mb: 32768
    runtime: '24h'

multiqc:
    threads: 1
    mem_mb: 65536
    runtime: '12h'

align:
    threads: 16
    mem_mb: 36864
    runtime: '12h'

samtools_stats:
    threads: 1
    mem_mb: 8192
    runtime: '5h'

qualimap:
    threads: 8
    mem_mb: 8192
    runtime: '5h'
